apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po-wget
spec:
  containers:
    -
      args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
      command:
        - /usr/bin/php
      end:
        -
          name: author
          value: Escallada
      image: escallada/phpinfo:latest
      name: phpinfo-container
      ports:
        -
          containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /app/
          name: public
          readOnly: true
      workingDir: /app/
  initContainers:
    -
      args:
        - wget https://raw.githubusercontent.com/jose-escallada/phpinfo/2021-09-santander/src/index.php ;
      command:
        - /bin/sh
        - -c
      env:
        -
          name: author
          value: Escallada
      image: library/busybox:1.33.1-uclibc@sha256:829b46ecdbdda76abbfe33b8a66332a02aa1593acc434541b4069ce5927bb811
      name: phpinfo-git
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /public/
          name: public
          readOnly: false
      workingDir: /public/
  volumes:
    -  
      emptyDir:
        medium: ''
        sizeLimit: 1M
      name: public    
status: {}
